# Java Tracing Test
#com.instana.plugin.javatrace:
#  instrumentation:
#    # Lightweight Bytecode Instrumentation, enabled by default
#    # Disabling currently requires an agent restart
#    enabled: disable

# Hardware & Zone
com.instana.plugin.generic.hardware:
  enabled: true # disabled by default
  availability-zone: 'webmethods'
