#!/bin/sh

# Assisted by watsonx Code Assistant
# Code generated by WCA@IBM in this programming language is not approved for use in IBM product development.

#!/bin/sh

# Get the current timestamp in the desired format (YYYYMMDD_HHmmss)
timestamp=$(date +%Y%m%d_%H%M%S)

# Define the temporary folder name using the timestamp
temp_folder="/tmp/temp_folder_$timestamp"

# Create the new temporary folder
mkdir -p "${temp_folder}/agw-audit"
mkdir -p "${temp_folder}/agw"
mkdir -p "${temp_folder}/esb-audit"
mkdir -p "${temp_folder}/esb"

# Output the newly created temporary folder path
echo "New temporary folder created at: ${temp_folder}"

volDir="/home/webmethods/.local/share/docker/volumes"
agwAuditDir="${volDir}/01e2em_instana_apigw-vm1-audit/_data"
agwLogsDir="${volDir}/01e2em_instana_apigw-vm1-wm-home/_data/IntegrationServer/logs"
esbAuditDir="${volDir}/01e2em_instana_esb-vm1-audit/_data"
esbLogsDir="${volDir}/01e2em_instana_esb-vm1-wm-home/_data/IntegrationServer/logs"

cp -r "${agwAuditDir}"/* "${temp_folder}"/agw-audit/
cp -r "${esbAuditDir}"/* "${temp_folder}"/esb-audit/

cp -r "${agwLogsDir}"/* "${temp_folder}"/agw/
cp -r "${esbLogsDir}"/* "${temp_folder}"/esb/

cp /home/webmethods/WMUI/10.Labs/01.E2EM_Instana/local/otel/traces.json "${temp_folder}"/

# Assisted by watsonx Code Assistant
# Code generated by WCA@IBM in this programming language is not approved for use in IBM product development.

echo "Inspecting uh* jars in API Gateway installation" > "${temp_folder}"/shasums.txt
target_directory="${volDir}/01e2em_instana_apigw-vm1-wm-home/_data/"
# Use find to locate all .jar files in the target directory and its subdirectories
find "$target_directory" -type f -name "uh*.jar" -print0 | while IFS= read -r -d '' jar_file; do
    # Compute the SHA-256 checksum
    s=$(sha256sum "$jar_file")

    # Print a header for better readability (optional)
    echo "$(basename "$jar_file")-->$s" >> "${temp_folder}"/shasums.txt
done
echo "Inspecting uh* jars in ESB installation" >> "${temp_folder}"/shasums.txt
target_directory="${volDir}/01e2em_instana_esb-vm1-wm-home/_data/"
# Use find to locate all .jar files in the target directory and its subdirectories
find "$target_directory" -type f -name "uh*.jar" -print0 | while IFS= read -r -d '' jar_file; do
    # Compute the SHA-256 checksum
    s=$(sha256sum "$jar_file")

    # Print a header for better readability (optional)
    echo "$(basename "$jar_file")-->$s" >> "${temp_folder}"/shasums.txt
done

docker logs instana-agent > "${temp_folder}"/instana-agent.log 2>&1
docker logs lab01-otelc > "${temp_folder}"/otelc-agent.log 2>&1

tar czf "${temp_folder}.tgz" "${temp_folder}" --remove-files

