#!/bin/sh

## User MUST provide
export WMUI_DBSERVER_HOSTNAME="${WMUI_DBSERVER_HOSTNAME:-ora-db-server}"
export WMUI_DBSERVER_SERVICE_NAME="${WMUI_DBSERVER_SERVICE_NAME:-xe}"
export WMUI_DBSERVER_USER_NAME="${WMUI_DBSERVER_USER_NAME:-webm}"
export WMUI_DBSERVER_PASSWORD="${WMUI_DBSERVER_PASSWORD:-webm}"

## User MUST provide only IF WMUI_DATABASE_ALREADY_CREATED is not 0
export WMUI_DBSERVER_SA_PASSWORD="${WMUI_DBSERVER_SA_PASSWORD:-webm}"

## User MAY provide
export WMUI_CACHE_HOME="${WMUI_CACHE_HOME:-/tmp/WMUI_CACHE}"
export WMUI_INSTALL_InstallDir="${WMUI_INSTALL_InstallDir:-/opt/sag/products}"
# 0 means DB was not created, thus create now
export WMUI_DATABASE_ALREADY_CREATED="${WMUI_DATABASE_ALREADY_CREATED:-0}"
export WMUI_DBSERVER_PORT="${WMUI_DBSERVER_PORT:-1521}"
# By default create all components
export WMUI_DBC_COMPONENT_NAME="${WMUI_DBC_COMPONENT_NAME:-All}"
# By default create the latest version
export WMUI_DBC_COMPONENT_VERSION="${WMUI_DBC_COMPONENT_VERSION:-latest}"

# WIP
export WMUI_ORACLE_STORAGE_TABLESPACE_DIR="${WMUI_ORACLE_STORAGE_TABLESPACE_DIR:-/tmp}"