#!/bin/sh

export WMUI_APIGW_OLD_ADMINISTRATOR_PASSWORD=${WMUI_APIGW_OLD_ADMINISTRATOR_PASSWORD:-"manage"}
export WMUI_APIGW_NEW_ADMINISTRATOR_PASSWORD=${WMUI_APIGW_NEW_ADMINISTRATOR_PASSWORD:-"manage1"}

export WMUI_APIGW_URL_PROTOCOL=${WMUI_APIGW_URL_PROTOCOL:-"http"}
export WMUI_APIGW_DOMAINNAME=${WMUI_APIGW_DOMAINNAME:-"localhost"}
export WMUI_APIGW_SERVICE_PORT=${WMUI_APIGW_SERVICE_PORT:-"5555"}
