
volumes:
  install-home: {}
  sum-home: {}
  audit: {}

networks:
    n1:
      external: false
services:
  apigw1:
    build:
      context: ${H_WMUI_HOME}/09.utils/container-images/ubi/vm-emulator
      args:
        - __audit_home_dir=${WMUI_AUDIT_BASE_DIR}
        - __install_dir=${WMUI_INSTALL_INSTALL_DIR}
        - __upd_mgr_home_dir=${WMUI_UPD_MGR_HOME}
        - __user_home=${WMUI_USER_HOME}
    image: local/api-gw-1101-default-test-1
    container_name: api-gw-1101-default-test-1
    hostname: api-gw-1101-default-test-1
    ulimits:
      nproc: 4096
      nofile: 65536
    volumes:
      # the following must match the Dokerfile folders, otherwise permissions on FS will not work
      - install-home:${WMUI_INSTALL_INSTALL_DIR}
      - sum-home:${WMUI_UPD_MGR_HOME}
      - audit:${WMUI_AUDIT_BASE_DIR}
      - ./scripts:${WMUI_TEST_LOCAL_SCRIPTS_DIR}
      # These must be provided, they are prerequisites
      - ${H_WMUI_FIXES_IMAGE_FILE}:${WMUI_PATCH_FIXES_IMAGE_FILE}
      - ${H_WMUI_PRODUCTS_IMAGE_FILE}:${WMUI_INSTALL_IMAGE_FILE}
      - ${H_WMUI_UPD_MGR_BOOTSTRAP_BIN}:${WMUI_PATCH_UPD_MGR_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMUI_INSTALLER_BIN}:${WMUI_INSTALL_INSTALLER_BIN_MOUNT_POINT}
      - ../../../../../:${WMUI_HOME}
    environment:
      # we declare WMUI_HOME because we mount it here
      - WMUI_HOME
      # setupFunctions prerequisites map, declared here because provided by host
      - WMUI_INSTALL_INSTALLER_BIN
      - WMUI_INSTALL_IMAGE_FILE
      - WMUI_PATCH_UPD_MGR_BOOTSTRAP_BIN
      - WMUI_PATCH_FIXES_IMAGE_FILE
      - WMUI_INSTALL_INSTALL_DIR
      # declare install dir and SUM dir because they are mounted here
      # setup template specifics - license provided by host
      - WMUI_INSTALL_INSTALLER_BIN_MOUNT_POINT
      - WMUI_PATCH_UPD_MGR_BOOTSTRAP_BIN_MOUNT_POINT
      - WMUI_PATCH_AVAILABLE
      - WMUI_ONLINE_MODE
      - WMUI_SDC_ONLINE_MODE
      - WMUI_DEBUG_ON
      - WMUI_WORK_DIR
      # host related, but still needed
      - H_WMUI_PORT_PREFIX
    ports:
      - "${H_WMUI_PORT_PREFIX}20:9240"
      - "${H_WMUI_PORT_PREFIX}73:9073"
      - "${H_WMUI_PORT_PREFIX}72:9072"
      - "${H_WMUI_PORT_PREFIX}55:5555"
    networks:
      n1:
        aliases:
          - apigw-server
    entrypoint: ${WMUI_TEST_LOCAL_SCRIPTS_DIR}/containerEntrypoint.sh
  elasticvue:
    image: cars10/elasticvue
    ports:
      - "${H_WMUI_PORT_PREFIX}80:8080"
    networks:
      n1:
        aliases:
          - elasticvue
