#!/bin/sh

export WMUI_POST_TC_SERVER_LOGS_DIR=${WMUI_TC_SERVER_LOGS_DIR:-"./logs"}
export WMUI_POST_TC_SERVER_DATA_DIR=${WMUI_TC_SERVER_DATA_DIR:-"./data"}
export WMUI_POST_TC_SERVER_PORT=${WMUI_TC_SERVER_PORT:-"9510"}
export WMUI_POST_TC_SERVER_GROUP_PORT=${WMUI_TC_SERVER_GROUP_PORT:-"9540"}
export WMUI_POST_TC_SERVER_OFFHEAP_MEM_DATA_SIZE=${WMUI_TC_SERVER_OFFHEAP_MEM_DATA_SIZE:-"2048m"}
