CREATE TABLESPACE WEBMDATA
DATAFILE '/opt/oracle/oradata/FREE/wmdata.dbf'
SIZE 100M
AUTOEXTEND ON
NEXT 10M
MAXSIZE UNLIMITED;

CREATE TABLESPACE WEBMINDX
DATAFILE '/opt/oracle/oradata/FREE/wmindx.dbf'
SIZE 50M
AUTOEXTEND ON
NEXT 5M
MAXSIZE UNLIMITED;

CREATE TABLESPACE WEBMBLOB
DATAFILE '/opt/oracle/oradata/FREE/wmblob.dbf'
SIZE 50M
AUTOEXTEND ON
NEXT 5M
MAXSIZE UNLIMITED;

CREATE TABLESPACE WEBMARCDATA
DATAFILE '/opt/oracle/oradata/FREE/wmarcdata.dbf'
SIZE 100M
AUTOEXTEND ON
NEXT 10M
MAXSIZE UNLIMITED;

CREATE TABLESPACE WEBMARCINDX
DATAFILE '/opt/oracle/oradata/FREE/wmarcindx.dbf'
SIZE 50M
AUTOEXTEND ON
NEXT 5M
MAXSIZE UNLIMITED;

CREATE TABLESPACE WEBMARCBLOB
DATAFILE '/opt/oracle/oradata/FREE/wmarcblob.dbf'
SIZE 50M
AUTOEXTEND ON
NEXT 5M
MAXSIZE UNLIMITED;

-- Made with Bob
