receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors: {}
exporters:
  debug:
    verbosity: detailed
  file:
    path: /tmp/traces.json
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ debug, file ]
    metrics:
      receivers: [ otlp ]
      exporters: [ debug, file ]
    logs:
      receivers: [ otlp ]
      exporters: [ debug, file ]
